controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# app_index: #route name
#     path: /
#     controller: App\Controller\HelloController::index **route of the controller we want to use path\folder_with_controller\controller_name::method**
